package com.zhht.project.bean;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class AppCarExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table app_car
     *
     * @mbg.generated Fri Jun 09 14:10:38 CST 2017
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table app_car
     *
     * @mbg.generated Fri Jun 09 14:10:38 CST 2017
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table app_car
     *
     * @mbg.generated Fri Jun 09 14:10:38 CST 2017
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_car
     *
     * @mbg.generated Fri Jun 09 14:10:38 CST 2017
     */
    public AppCarExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_car
     *
     * @mbg.generated Fri Jun 09 14:10:38 CST 2017
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_car
     *
     * @mbg.generated Fri Jun 09 14:10:38 CST 2017
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_car
     *
     * @mbg.generated Fri Jun 09 14:10:38 CST 2017
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_car
     *
     * @mbg.generated Fri Jun 09 14:10:38 CST 2017
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_car
     *
     * @mbg.generated Fri Jun 09 14:10:38 CST 2017
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_car
     *
     * @mbg.generated Fri Jun 09 14:10:38 CST 2017
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_car
     *
     * @mbg.generated Fri Jun 09 14:10:38 CST 2017
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_car
     *
     * @mbg.generated Fri Jun 09 14:10:38 CST 2017
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_car
     *
     * @mbg.generated Fri Jun 09 14:10:38 CST 2017
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_car
     *
     * @mbg.generated Fri Jun 09 14:10:38 CST 2017
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table app_car
     *
     * @mbg.generated Fri Jun 09 14:10:38 CST 2017
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andCarIdIsNull() {
            addCriterion("CAR_ID is null");
            return (Criteria) this;
        }

        public Criteria andCarIdIsNotNull() {
            addCriterion("CAR_ID is not null");
            return (Criteria) this;
        }

        public Criteria andCarIdEqualTo(String value) {
            addCriterion("CAR_ID =", value, "carId");
            return (Criteria) this;
        }

        public Criteria andCarIdNotEqualTo(String value) {
            addCriterion("CAR_ID <>", value, "carId");
            return (Criteria) this;
        }

        public Criteria andCarIdGreaterThan(String value) {
            addCriterion("CAR_ID >", value, "carId");
            return (Criteria) this;
        }

        public Criteria andCarIdGreaterThanOrEqualTo(String value) {
            addCriterion("CAR_ID >=", value, "carId");
            return (Criteria) this;
        }

        public Criteria andCarIdLessThan(String value) {
            addCriterion("CAR_ID <", value, "carId");
            return (Criteria) this;
        }

        public Criteria andCarIdLessThanOrEqualTo(String value) {
            addCriterion("CAR_ID <=", value, "carId");
            return (Criteria) this;
        }

        public Criteria andCarIdLike(String value) {
            addCriterion("CAR_ID like", value, "carId");
            return (Criteria) this;
        }

        public Criteria andCarIdNotLike(String value) {
            addCriterion("CAR_ID not like", value, "carId");
            return (Criteria) this;
        }

        public Criteria andCarIdIn(List<String> values) {
            addCriterion("CAR_ID in", values, "carId");
            return (Criteria) this;
        }

        public Criteria andCarIdNotIn(List<String> values) {
            addCriterion("CAR_ID not in", values, "carId");
            return (Criteria) this;
        }

        public Criteria andCarIdBetween(String value1, String value2) {
            addCriterion("CAR_ID between", value1, value2, "carId");
            return (Criteria) this;
        }

        public Criteria andCarIdNotBetween(String value1, String value2) {
            addCriterion("CAR_ID not between", value1, value2, "carId");
            return (Criteria) this;
        }

        public Criteria andAppUserIdIsNull() {
            addCriterion("APP_USER_ID is null");
            return (Criteria) this;
        }

        public Criteria andAppUserIdIsNotNull() {
            addCriterion("APP_USER_ID is not null");
            return (Criteria) this;
        }

        public Criteria andAppUserIdEqualTo(Long value) {
            addCriterion("APP_USER_ID =", value, "appUserId");
            return (Criteria) this;
        }

        public Criteria andAppUserIdNotEqualTo(Long value) {
            addCriterion("APP_USER_ID <>", value, "appUserId");
            return (Criteria) this;
        }

        public Criteria andAppUserIdGreaterThan(Long value) {
            addCriterion("APP_USER_ID >", value, "appUserId");
            return (Criteria) this;
        }

        public Criteria andAppUserIdGreaterThanOrEqualTo(Long value) {
            addCriterion("APP_USER_ID >=", value, "appUserId");
            return (Criteria) this;
        }

        public Criteria andAppUserIdLessThan(Long value) {
            addCriterion("APP_USER_ID <", value, "appUserId");
            return (Criteria) this;
        }

        public Criteria andAppUserIdLessThanOrEqualTo(Long value) {
            addCriterion("APP_USER_ID <=", value, "appUserId");
            return (Criteria) this;
        }

        public Criteria andAppUserIdIn(List<Long> values) {
            addCriterion("APP_USER_ID in", values, "appUserId");
            return (Criteria) this;
        }

        public Criteria andAppUserIdNotIn(List<Long> values) {
            addCriterion("APP_USER_ID not in", values, "appUserId");
            return (Criteria) this;
        }

        public Criteria andAppUserIdBetween(Long value1, Long value2) {
            addCriterion("APP_USER_ID between", value1, value2, "appUserId");
            return (Criteria) this;
        }

        public Criteria andAppUserIdNotBetween(Long value1, Long value2) {
            addCriterion("APP_USER_ID not between", value1, value2, "appUserId");
            return (Criteria) this;
        }

        public Criteria andPlateNumberIsNull() {
            addCriterion("PLATE_NUMBER is null");
            return (Criteria) this;
        }

        public Criteria andPlateNumberIsNotNull() {
            addCriterion("PLATE_NUMBER is not null");
            return (Criteria) this;
        }

        public Criteria andPlateNumberEqualTo(String value) {
            addCriterion("PLATE_NUMBER =", value, "plateNumber");
            return (Criteria) this;
        }

        public Criteria andPlateNumberNotEqualTo(String value) {
            addCriterion("PLATE_NUMBER <>", value, "plateNumber");
            return (Criteria) this;
        }

        public Criteria andPlateNumberGreaterThan(String value) {
            addCriterion("PLATE_NUMBER >", value, "plateNumber");
            return (Criteria) this;
        }

        public Criteria andPlateNumberGreaterThanOrEqualTo(String value) {
            addCriterion("PLATE_NUMBER >=", value, "plateNumber");
            return (Criteria) this;
        }

        public Criteria andPlateNumberLessThan(String value) {
            addCriterion("PLATE_NUMBER <", value, "plateNumber");
            return (Criteria) this;
        }

        public Criteria andPlateNumberLessThanOrEqualTo(String value) {
            addCriterion("PLATE_NUMBER <=", value, "plateNumber");
            return (Criteria) this;
        }

        public Criteria andPlateNumberLike(String value) {
            addCriterion("PLATE_NUMBER like", value, "plateNumber");
            return (Criteria) this;
        }

        public Criteria andPlateNumberNotLike(String value) {
            addCriterion("PLATE_NUMBER not like", value, "plateNumber");
            return (Criteria) this;
        }

        public Criteria andPlateNumberIn(List<String> values) {
            addCriterion("PLATE_NUMBER in", values, "plateNumber");
            return (Criteria) this;
        }

        public Criteria andPlateNumberNotIn(List<String> values) {
            addCriterion("PLATE_NUMBER not in", values, "plateNumber");
            return (Criteria) this;
        }

        public Criteria andPlateNumberBetween(String value1, String value2) {
            addCriterion("PLATE_NUMBER between", value1, value2, "plateNumber");
            return (Criteria) this;
        }

        public Criteria andPlateNumberNotBetween(String value1, String value2) {
            addCriterion("PLATE_NUMBER not between", value1, value2, "plateNumber");
            return (Criteria) this;
        }

        public Criteria andCarTypeIsNull() {
            addCriterion("CAR_TYPE is null");
            return (Criteria) this;
        }

        public Criteria andCarTypeIsNotNull() {
            addCriterion("CAR_TYPE is not null");
            return (Criteria) this;
        }

        public Criteria andCarTypeEqualTo(Boolean value) {
            addCriterion("CAR_TYPE =", value, "carType");
            return (Criteria) this;
        }

        public Criteria andCarTypeNotEqualTo(Boolean value) {
            addCriterion("CAR_TYPE <>", value, "carType");
            return (Criteria) this;
        }

        public Criteria andCarTypeGreaterThan(Boolean value) {
            addCriterion("CAR_TYPE >", value, "carType");
            return (Criteria) this;
        }

        public Criteria andCarTypeGreaterThanOrEqualTo(Boolean value) {
            addCriterion("CAR_TYPE >=", value, "carType");
            return (Criteria) this;
        }

        public Criteria andCarTypeLessThan(Boolean value) {
            addCriterion("CAR_TYPE <", value, "carType");
            return (Criteria) this;
        }

        public Criteria andCarTypeLessThanOrEqualTo(Boolean value) {
            addCriterion("CAR_TYPE <=", value, "carType");
            return (Criteria) this;
        }

        public Criteria andCarTypeIn(List<Boolean> values) {
            addCriterion("CAR_TYPE in", values, "carType");
            return (Criteria) this;
        }

        public Criteria andCarTypeNotIn(List<Boolean> values) {
            addCriterion("CAR_TYPE not in", values, "carType");
            return (Criteria) this;
        }

        public Criteria andCarTypeBetween(Boolean value1, Boolean value2) {
            addCriterion("CAR_TYPE between", value1, value2, "carType");
            return (Criteria) this;
        }

        public Criteria andCarTypeNotBetween(Boolean value1, Boolean value2) {
            addCriterion("CAR_TYPE not between", value1, value2, "carType");
            return (Criteria) this;
        }

        public Criteria andIsBindIsNull() {
            addCriterion("IS_BIND is null");
            return (Criteria) this;
        }

        public Criteria andIsBindIsNotNull() {
            addCriterion("IS_BIND is not null");
            return (Criteria) this;
        }

        public Criteria andIsBindEqualTo(Boolean value) {
            addCriterion("IS_BIND =", value, "isBind");
            return (Criteria) this;
        }

        public Criteria andIsBindNotEqualTo(Boolean value) {
            addCriterion("IS_BIND <>", value, "isBind");
            return (Criteria) this;
        }

        public Criteria andIsBindGreaterThan(Boolean value) {
            addCriterion("IS_BIND >", value, "isBind");
            return (Criteria) this;
        }

        public Criteria andIsBindGreaterThanOrEqualTo(Boolean value) {
            addCriterion("IS_BIND >=", value, "isBind");
            return (Criteria) this;
        }

        public Criteria andIsBindLessThan(Boolean value) {
            addCriterion("IS_BIND <", value, "isBind");
            return (Criteria) this;
        }

        public Criteria andIsBindLessThanOrEqualTo(Boolean value) {
            addCriterion("IS_BIND <=", value, "isBind");
            return (Criteria) this;
        }

        public Criteria andIsBindIn(List<Boolean> values) {
            addCriterion("IS_BIND in", values, "isBind");
            return (Criteria) this;
        }

        public Criteria andIsBindNotIn(List<Boolean> values) {
            addCriterion("IS_BIND not in", values, "isBind");
            return (Criteria) this;
        }

        public Criteria andIsBindBetween(Boolean value1, Boolean value2) {
            addCriterion("IS_BIND between", value1, value2, "isBind");
            return (Criteria) this;
        }

        public Criteria andIsBindNotBetween(Boolean value1, Boolean value2) {
            addCriterion("IS_BIND not between", value1, value2, "isBind");
            return (Criteria) this;
        }

        public Criteria andIsValidIsNull() {
            addCriterion("IS_VALID is null");
            return (Criteria) this;
        }

        public Criteria andIsValidIsNotNull() {
            addCriterion("IS_VALID is not null");
            return (Criteria) this;
        }

        public Criteria andIsValidEqualTo(Boolean value) {
            addCriterion("IS_VALID =", value, "isValid");
            return (Criteria) this;
        }

        public Criteria andIsValidNotEqualTo(Boolean value) {
            addCriterion("IS_VALID <>", value, "isValid");
            return (Criteria) this;
        }

        public Criteria andIsValidGreaterThan(Boolean value) {
            addCriterion("IS_VALID >", value, "isValid");
            return (Criteria) this;
        }

        public Criteria andIsValidGreaterThanOrEqualTo(Boolean value) {
            addCriterion("IS_VALID >=", value, "isValid");
            return (Criteria) this;
        }

        public Criteria andIsValidLessThan(Boolean value) {
            addCriterion("IS_VALID <", value, "isValid");
            return (Criteria) this;
        }

        public Criteria andIsValidLessThanOrEqualTo(Boolean value) {
            addCriterion("IS_VALID <=", value, "isValid");
            return (Criteria) this;
        }

        public Criteria andIsValidIn(List<Boolean> values) {
            addCriterion("IS_VALID in", values, "isValid");
            return (Criteria) this;
        }

        public Criteria andIsValidNotIn(List<Boolean> values) {
            addCriterion("IS_VALID not in", values, "isValid");
            return (Criteria) this;
        }

        public Criteria andIsValidBetween(Boolean value1, Boolean value2) {
            addCriterion("IS_VALID between", value1, value2, "isValid");
            return (Criteria) this;
        }

        public Criteria andIsValidNotBetween(Boolean value1, Boolean value2) {
            addCriterion("IS_VALID not between", value1, value2, "isValid");
            return (Criteria) this;
        }

        public Criteria andTsIsNull() {
            addCriterion("TS is null");
            return (Criteria) this;
        }

        public Criteria andTsIsNotNull() {
            addCriterion("TS is not null");
            return (Criteria) this;
        }

        public Criteria andTsEqualTo(Date value) {
            addCriterion("TS =", value, "ts");
            return (Criteria) this;
        }

        public Criteria andTsNotEqualTo(Date value) {
            addCriterion("TS <>", value, "ts");
            return (Criteria) this;
        }

        public Criteria andTsGreaterThan(Date value) {
            addCriterion("TS >", value, "ts");
            return (Criteria) this;
        }

        public Criteria andTsGreaterThanOrEqualTo(Date value) {
            addCriterion("TS >=", value, "ts");
            return (Criteria) this;
        }

        public Criteria andTsLessThan(Date value) {
            addCriterion("TS <", value, "ts");
            return (Criteria) this;
        }

        public Criteria andTsLessThanOrEqualTo(Date value) {
            addCriterion("TS <=", value, "ts");
            return (Criteria) this;
        }

        public Criteria andTsIn(List<Date> values) {
            addCriterion("TS in", values, "ts");
            return (Criteria) this;
        }

        public Criteria andTsNotIn(List<Date> values) {
            addCriterion("TS not in", values, "ts");
            return (Criteria) this;
        }

        public Criteria andTsBetween(Date value1, Date value2) {
            addCriterion("TS between", value1, value2, "ts");
            return (Criteria) this;
        }

        public Criteria andTsNotBetween(Date value1, Date value2) {
            addCriterion("TS not between", value1, value2, "ts");
            return (Criteria) this;
        }

        public Criteria andIsFirstBindIsNull() {
            addCriterion("IS_FIRST_BIND is null");
            return (Criteria) this;
        }

        public Criteria andIsFirstBindIsNotNull() {
            addCriterion("IS_FIRST_BIND is not null");
            return (Criteria) this;
        }

        public Criteria andIsFirstBindEqualTo(Boolean value) {
            addCriterion("IS_FIRST_BIND =", value, "isFirstBind");
            return (Criteria) this;
        }

        public Criteria andIsFirstBindNotEqualTo(Boolean value) {
            addCriterion("IS_FIRST_BIND <>", value, "isFirstBind");
            return (Criteria) this;
        }

        public Criteria andIsFirstBindGreaterThan(Boolean value) {
            addCriterion("IS_FIRST_BIND >", value, "isFirstBind");
            return (Criteria) this;
        }

        public Criteria andIsFirstBindGreaterThanOrEqualTo(Boolean value) {
            addCriterion("IS_FIRST_BIND >=", value, "isFirstBind");
            return (Criteria) this;
        }

        public Criteria andIsFirstBindLessThan(Boolean value) {
            addCriterion("IS_FIRST_BIND <", value, "isFirstBind");
            return (Criteria) this;
        }

        public Criteria andIsFirstBindLessThanOrEqualTo(Boolean value) {
            addCriterion("IS_FIRST_BIND <=", value, "isFirstBind");
            return (Criteria) this;
        }

        public Criteria andIsFirstBindIn(List<Boolean> values) {
            addCriterion("IS_FIRST_BIND in", values, "isFirstBind");
            return (Criteria) this;
        }

        public Criteria andIsFirstBindNotIn(List<Boolean> values) {
            addCriterion("IS_FIRST_BIND not in", values, "isFirstBind");
            return (Criteria) this;
        }

        public Criteria andIsFirstBindBetween(Boolean value1, Boolean value2) {
            addCriterion("IS_FIRST_BIND between", value1, value2, "isFirstBind");
            return (Criteria) this;
        }

        public Criteria andIsFirstBindNotBetween(Boolean value1, Boolean value2) {
            addCriterion("IS_FIRST_BIND not between", value1, value2, "isFirstBind");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table app_car
     *
     * @mbg.generated do_not_delete_during_merge Fri Jun 09 14:10:38 CST 2017
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table app_car
     *
     * @mbg.generated Fri Jun 09 14:10:38 CST 2017
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}