package com.zhht.project.bean;

import java.io.Serializable;
import java.util.Date;

public class AppCar implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_car.CAR_ID
     *
     * @mbg.generated Fri Jun 09 14:10:38 CST 2017
     */
    private String carId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_car.APP_USER_ID
     *
     * @mbg.generated Fri Jun 09 14:10:38 CST 2017
     */
    private Long appUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_car.PLATE_NUMBER
     *
     * @mbg.generated Fri Jun 09 14:10:38 CST 2017
     */
    private String plateNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_car.CAR_TYPE
     *
     * @mbg.generated Fri Jun 09 14:10:38 CST 2017
     */
    private Boolean carType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_car.IS_BIND
     *
     * @mbg.generated Fri Jun 09 14:10:38 CST 2017
     */
    private Boolean isBind;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_car.IS_VALID
     *
     * @mbg.generated Fri Jun 09 14:10:38 CST 2017
     */
    private Boolean isValid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_car.TS
     *
     * @mbg.generated Fri Jun 09 14:10:38 CST 2017
     */
    private Date ts;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_car.IS_FIRST_BIND
     *
     * @mbg.generated Fri Jun 09 14:10:38 CST 2017
     */
    private Boolean isFirstBind;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table app_car
     *
     * @mbg.generated Fri Jun 09 14:10:38 CST 2017
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_car.CAR_ID
     *
     * @return the value of app_car.CAR_ID
     *
     * @mbg.generated Fri Jun 09 14:10:38 CST 2017
     */
    public String getCarId() {
        return carId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_car.CAR_ID
     *
     * @param carId the value for app_car.CAR_ID
     *
     * @mbg.generated Fri Jun 09 14:10:38 CST 2017
     */
    public void setCarId(String carId) {
        this.carId = carId == null ? null : carId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_car.APP_USER_ID
     *
     * @return the value of app_car.APP_USER_ID
     *
     * @mbg.generated Fri Jun 09 14:10:38 CST 2017
     */
    public Long getAppUserId() {
        return appUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_car.APP_USER_ID
     *
     * @param appUserId the value for app_car.APP_USER_ID
     *
     * @mbg.generated Fri Jun 09 14:10:38 CST 2017
     */
    public void setAppUserId(Long appUserId) {
        this.appUserId = appUserId;
    }

    public AppCar() {
		super();
		// TODO Auto-generated constructor stub
	}

	public AppCar(String carId, Long appUserId, String plateNumber,
			Boolean carType, Boolean isBind, Boolean isValid, Date ts,
			Boolean isFirstBind) {
		super();
		this.carId = carId;
		this.appUserId = appUserId;
		this.plateNumber = plateNumber;
		this.carType = carType;
		this.isBind = isBind;
		this.isValid = isValid;
		this.ts = ts;
		this.isFirstBind = isFirstBind;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_car.PLATE_NUMBER
     *
     * @return the value of app_car.PLATE_NUMBER
     *
     * @mbg.generated Fri Jun 09 14:10:38 CST 2017
     */
    public String getPlateNumber() {
        return plateNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_car.PLATE_NUMBER
     *
     * @param plateNumber the value for app_car.PLATE_NUMBER
     *
     * @mbg.generated Fri Jun 09 14:10:38 CST 2017
     */
    public void setPlateNumber(String plateNumber) {
        this.plateNumber = plateNumber == null ? null : plateNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_car.CAR_TYPE
     *
     * @return the value of app_car.CAR_TYPE
     *
     * @mbg.generated Fri Jun 09 14:10:38 CST 2017
     */
    public Boolean getCarType() {
        return carType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_car.CAR_TYPE
     *
     * @param carType the value for app_car.CAR_TYPE
     *
     * @mbg.generated Fri Jun 09 14:10:38 CST 2017
     */
    public void setCarType(Boolean carType) {
        this.carType = carType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_car.IS_BIND
     *
     * @return the value of app_car.IS_BIND
     *
     * @mbg.generated Fri Jun 09 14:10:38 CST 2017
     */
    public Boolean getIsBind() {
        return isBind;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_car.IS_BIND
     *
     * @param isBind the value for app_car.IS_BIND
     *
     * @mbg.generated Fri Jun 09 14:10:38 CST 2017
     */
    public void setIsBind(Boolean isBind) {
        this.isBind = isBind;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_car.IS_VALID
     *
     * @return the value of app_car.IS_VALID
     *
     * @mbg.generated Fri Jun 09 14:10:38 CST 2017
     */
    public Boolean getIsValid() {
        return isValid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_car.IS_VALID
     *
     * @param isValid the value for app_car.IS_VALID
     *
     * @mbg.generated Fri Jun 09 14:10:38 CST 2017
     */
    public void setIsValid(Boolean isValid) {
        this.isValid = isValid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_car.TS
     *
     * @return the value of app_car.TS
     *
     * @mbg.generated Fri Jun 09 14:10:38 CST 2017
     */
    public Date getTs() {
        return ts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_car.TS
     *
     * @param ts the value for app_car.TS
     *
     * @mbg.generated Fri Jun 09 14:10:38 CST 2017
     */
    public void setTs(Date ts) {
        this.ts = ts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_car.IS_FIRST_BIND
     *
     * @return the value of app_car.IS_FIRST_BIND
     *
     * @mbg.generated Fri Jun 09 14:10:38 CST 2017
     */
    public Boolean getIsFirstBind() {
        return isFirstBind;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_car.IS_FIRST_BIND
     *
     * @param isFirstBind the value for app_car.IS_FIRST_BIND
     *
     * @mbg.generated Fri Jun 09 14:10:38 CST 2017
     */
    public void setIsFirstBind(Boolean isFirstBind) {
        this.isFirstBind = isFirstBind;
    }

    public static long getSerialversionuid() {
        return serialVersionUID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_car
     *
     * @mbg.generated Fri Jun 09 14:10:38 CST 2017
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", carId=").append(carId);
        sb.append(", appUserId=").append(appUserId);
        sb.append(", plateNumber=").append(plateNumber);
        sb.append(", carType=").append(carType);
        sb.append(", isBind=").append(isBind);
        sb.append(", isValid=").append(isValid);
        sb.append(", ts=").append(ts);
        sb.append(", isFirstBind=").append(isFirstBind);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}