package com.zhht.test.bean;

import java.io.Serializable;

public class Test_Order implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_order.id
     *
     * @mbg.generated Mon Jan 15 16:43:47 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_order.order_code
     *
     * @mbg.generated Mon Jan 15 16:43:47 CST 2018
     */
    private String orderCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table test_order
     *
     * @mbg.generated Mon Jan 15 16:43:47 CST 2018
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_order.id
     *
     * @return the value of test_order.id
     *
     * @mbg.generated Mon Jan 15 16:43:47 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_order.id
     *
     * @param id the value for test_order.id
     *
     * @mbg.generated Mon Jan 15 16:43:47 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_order.order_code
     *
     * @return the value of test_order.order_code
     *
     * @mbg.generated Mon Jan 15 16:43:47 CST 2018
     */
    public String getOrderCode() {
        return orderCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_order.order_code
     *
     * @param orderCode the value for test_order.order_code
     *
     * @mbg.generated Mon Jan 15 16:43:47 CST 2018
     */
    public void setOrderCode(String orderCode) {
        this.orderCode = orderCode == null ? null : orderCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_order
     *
     * @mbg.generated Mon Jan 15 16:43:47 CST 2018
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", orderCode=").append(orderCode);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}