package com.zhht.test.dao;

import com.zhht.test.bean.Test_Order;
import com.zhht.test.bean.Test_OrderExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface Test_OrderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_order
     *
     * @mbg.generated Mon Jan 15 16:43:47 CST 2018
     */
    long countByExample(Test_OrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_order
     *
     * @mbg.generated Mon Jan 15 16:43:47 CST 2018
     */
    int deleteByExample(Test_OrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_order
     *
     * @mbg.generated Mon Jan 15 16:43:47 CST 2018
     */
    int insert(Test_Order record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_order
     *
     * @mbg.generated Mon Jan 15 16:43:47 CST 2018
     */
    int insertSelective(Test_Order record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_order
     *
     * @mbg.generated Mon Jan 15 16:43:47 CST 2018
     */
    List<Test_Order> selectByExample(Test_OrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_order
     *
     * @mbg.generated Mon Jan 15 16:43:47 CST 2018
     */
    int updateByExampleSelective(@Param("record") Test_Order record, @Param("example") Test_OrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_order
     *
     * @mbg.generated Mon Jan 15 16:43:47 CST 2018
     */
    int updateByExample(@Param("record") Test_Order record, @Param("example") Test_OrderExample example);
}